---
apiVersion: "v1"
kind: "List"
items:
    - apiVersion: "v1"
      kind: "Service"
      metadata:
          labels:
              app: "quarkus-workshop-fight"
              version: "01"
              group: "cescoffier"
          name: "quarkus-workshop-fight"
      spec:
          ports:
              - name: "http"
                port: 8080
                targetPort: 8080
          selector:
              app: "quarkus-workshop-fight"
              version: "01"
              group: "cescoffier"
          type: "ClusterIP"
    - apiVersion: "apps/v1"
      kind: "Deployment"
      metadata:
          labels:
              app: "quarkus-workshop-fight"
              version: "01"
              group: "cescoffier"
          name: "quarkus-workshop-fight"
      spec:
          replicas: 1
          selector:
              matchLabels:
                  app: "quarkus-workshop-fight"
                  version: "01"
                  group: "cescoffier"
          template:
              metadata:
                  labels:
                      app: "quarkus-workshop-fight"
                      version: "01"
                      group: "cescoffier"
              spec:
                  containers:
                      - image: "cescoffier/quarkus-workshop-fight:latest"
                        imagePullPolicy: "IfNotPresent"
                        name: "quarkus-workshop-fight"
                        ports:
                            - containerPort: 8080
                              name: "http"
                              protocol: "TCP"
                        env:
                        - name: "KUBERNETES_NAMESPACE"
                          valueFrom:
                            fieldRef:
                              fieldPath: "metadata.namespace"
                        - name: QUARKUS_DATASOURCE_URL
                          valueFrom:
                            configMapKeyRef:
                              name: fight-config
                              key: database
                        - name: QUARKUS_HTTP_PORT
                          valueFrom:
                            configMapKeyRef:
                              name: fight-config
                              key: port
                        - name: IO_QUARKUS_WORKSHOP_SUPERHEROES_FIGHT_CLIENT_HEROSERVICE_MP_REST_URL
                          valueFrom:
                            configMapKeyRef:
                              name: fight-config
                              key: hero
                        - name: IO_QUARKUS_WORKSHOP_SUPERHEROES_FIGHT_CLIENT_VILLAINSERVICE_MP_REST_URL
                          valueFrom:
                            configMapKeyRef:
                              name: fight-config
                              key: villain
                        - name: KAFKA_BOOTSTRAP_SERVERS
                          valueFrom:
                              configMapKeyRef:
                                  name: fight-config
                                  key: kafka
